[package]
name = "editer"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7", optional = true, default-features = false }

[dev-dependencies]
editer = { path = ".", features = ["arrayvec"] }
arrayvec = "0.7"

[features]
default = ["alloc", "std"]
alloc = []
std = []
